name: polar_hr_monitor_analysis
description: Polar HR Monitor App
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  location: ^6.0.2
  flutter_reactive_ble: ^5.4.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  flutter_slidable: ^4.0.3
  flutter_svg: ^2.2.1
  fluttertoast: ^9.0.0
  google_fonts: ^6.3.2
  permission_handler: ^12.0.1
  sizer: ^3.1.3
  shared_preferences: ^2.2.3
  dio: ^5.4.0
  fl_chart: ^1.1.1
  universal_html: ^2.2.4

  # ✅ ใช้สำหรับเปิดหน้ารับค่า HR บน TV หรือ Browser
  url_launcher: ^6.3.0
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
